# Generated by Django 5.2.3 on 2025-06-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm11_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pimage',
            field=models.ImageField(default=0, upload_to='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='product name'),
        ),
    ]
