# Generated by Django 5.2.3 on 2025-06-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm11_app', '0002_product_pimage_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_jwellary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='product name')),
                ('price', models.FloatField()),
                ('pdetails', models.CharField(max_length=200)),
                ('cat', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('pimage', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.RenameModel(
            old_name='product',
            new_name='product_cloth',
        ),
    ]
