# Generated by Django 5.2.3 on 2025-06-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm11_app', '0003_product_jwellary_rename_product_product_cloth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_cloth',
            name='cat',
            field=models.IntegerField(choices=[(1, 'MENS_WEAR'), (2, 'WOMEN_WEAR'), (3, 'KIDS_WEAR')], verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='product_cloth',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Available'),
        ),
        migrations.AlterField(
            model_name='product_cloth',
            name='pdetails',
            field=models.CharField(max_length=200, verbose_name='product details'),
        ),
        migrations.AlterField(
            model_name='product_jwellary',
            name='cat',
            field=models.IntegerField(choices=[(4, 'MENS_JWELLARY'), (5, 'WOMEN_JWELLARY'), (6, 'KIDS_JWELLARY')], verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='product_jwellary',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Available'),
        ),
        migrations.AlterField(
            model_name='product_jwellary',
            name='pdetails',
            field=models.CharField(max_length=200, verbose_name='product details'),
        ),
    ]
