# Generated by Django 5.2.3 on 2025-06-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm11_app', '0005_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_type',
            field=models.CharField(default='cloth', max_length=50),
        ),
    ]
