# Generated by Django 5.2.3 on 2025-07-01 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm11_app', '0007_product_cloth_offer_price_product_cloth_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='pid',
        ),
        migrations.AddField(
            model_name='cart',
            name='cloth_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomm11_app.product_cloth'),
        ),
        migrations.AddField(
            model_name='cart',
            name='jwellary_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomm11_app.product_jwellary'),
        ),
    ]
