# Generated by Django 5.2.3 on 2025-07-02 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm11_app', '0008_remove_cart_pid_cart_cloth_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='uid',
            new_name='user',
        ),
    ]
