# Generated by Django 5.2.3 on 2025-07-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm11_app', '0011_order_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_jwellary',
            name='cat',
            field=models.IntegerField(choices=[(1, 'MENS_JWELLARY'), (2, 'WOMEN_JWELLARY'), (3, 'KIDS_JWELLARY')], verbose_name='category'),
        ),
    ]
