# Generated by Django 5.2.3 on 2025-07-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm11_app', '0012_alter_product_jwellary_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_jwellary',
            name='cat',
            field=models.IntegerField(choices=[(4, 'MENS_JWELLARY'), (5, 'WOMEN_JWELLARY'), (6, 'KIDS_JWELLARY')], verbose_name='category'),
        ),
    ]
